const RelayHub = artifacts.require('RelayHub')
const Penalizer = artifacts.require('Penalizer')
const SampleRecipient = artifacts.require('TestRecipient')
const SmartWallet = artifacts.require('SmartWallet')
const SmartWalletFactory = artifacts.require('SmartWalletFactory')
const CustomSmartWallet = artifacts.require('CustomSmartWallet')
const CustomSmartWalletFactory = artifacts.require('CustomSmartWalletFactory')
const DeployVerifier = artifacts.require('DeployVerifier')
const RelayVerifier = artifacts.require('RelayVerifier')

module.exports = async function (deployer) {
  await deployer.deploy(Penalizer)
  await deployer.deploy(RelayHub, Penalizer.address, 1, 1, 1, 1, 1)
  await deployer.deploy(SampleRecipient)
  await deployer.deploy(SmartWallet)
  await deployer.deploy(SmartWalletFactory, SmartWallet.address)
  await deployer.deploy(CustomSmartWallet)
  await deployer.deploy(CustomSmartWalletFactory, CustomSmartWallet.address)
  await deployer.deploy(DeployVerifier, SmartWalletFactory.address)
  await deployer.deploy(RelayVerifier, SmartWalletFactory.address)

  console.log('Done! Summary:')

  console.log('|============================|============================================|')
  console.log('| Contract                   | Address                                    |')
  console.log('|============================|============================================|')
  console.log(`| Penalizer                  | ${Penalizer.address} |`)
  console.log(`| RelayHub                   | ${RelayHub.address} |`)
  console.log(`| SampleRecipient            | ${SampleRecipient.address} |`)
  console.log(`| SmartWallet                | ${SmartWallet.address} |`)
  console.log(`| SmartWalletFactory         | ${SmartWalletFactory.address} |`)
  console.log(`| CustomSmartWallet          | ${CustomSmartWallet.address} |`)
  console.log(`| CustomSmartWalletFactory   | ${CustomSmartWalletFactory.address} |`)
  console.log(`| DeployVerifier             | ${DeployVerifier.address} |`)
  console.log(`| RelayVerifier              | ${RelayVerifier.address} |`)
  console.log('|============================|============================================|\n')
}
