#!/bin/bash

TOKEN_ADDRESSES="0x0E569743F573323F430B6E14E5676EB0cCAd03D9,0x1Af2844A588759D0DE58abD568ADD96BB8B3B6D8"
SMART_WALLET_DEPLOY_VERIFIER_ADDRESS="0x1938517B0762103d52590Ca21d459968c25c9E67"
SMART_WALLET_RELAY_VERIFIER_ADDRESS="0x74Dc4471FA8C8fBE09c7a0C400a0852b0A9d04b2"
CUSTOM_SMART_WALLET_DEPLOY_VERIFIER_ADDRESS="0x3eE31F6049065B616f85470985c0eF067f2bEbDE"
CUSTOM_SMART_WALLET_RELAY_VERIFIER_ADDRESS="0xDE8Ae20488BE104f0782C0126038b6682ECc1eC7"
NETWORK=33
RSK_HOST="rsk-node"
RSK_PORT=4444

TRUFFLE_CONFIG="module.exports = {  networks: { development: { host: '${RSK_HOST}', port: ${RSK_PORT}, network_id: '${NETWORK}' } } };"

echo "${TRUFFLE_CONFIG}" > truffle-config.js

cat > allowTokens.js << EOF
module.exports = async function(callback) {
  const smartWalletDeployVerifierAbi = require("../src/cli/compiled/DeployVerifier.json").abi;
  const customSmartWalletDeployVerifierAbi = require("../src/cli/compiled/CustomSmartWalletDeployVerifier.json").abi;
  const relayVerifierAbi = require("../src/cli/compiled/RelayVerifier.json").abi;

  const smartWalletDeployVerifier = await new web3.eth.Contract(smartWalletDeployVerifierAbi, "${SMART_WALLET_DEPLOY_VERIFIER_ADDRESS}");
  const smartWalletRelayVerifier = await new web3.eth.Contract(relayVerifierAbi, "${SMART_WALLET_RELAY_VERIFIER_ADDRESS}");
  const customSmartWalletDeployVerifier = await new web3.eth.Contract(customSmartWalletDeployVerifierAbi, "${CUSTOM_SMART_WALLET_DEPLOY_VERIFIER_ADDRESS}");
  const customSmartWalletRelayVerifier = await new web3.eth.Contract(relayVerifierAbi, "${CUSTOM_SMART_WALLET_RELAY_VERIFIER_ADDRESS}");

  const tokenAddresses = '${TOKEN_ADDRESSES}'.split(',');

  const accounts = await web3.eth.getAccounts();

  for (let tokenAddress of tokenAddresses) {
    console.log("Adding token with address " + tokenAddress + " to allowed tokens on smart wallet deploy verifier");
    try {
      await smartWalletDeployVerifier.methods.acceptToken(tokenAddress).send({from: accounts[0]});
    } catch (error) {
      console.error(error);
    }
    console.log("Adding token with address " + tokenAddress + " to allowed tokens on smart wallet relay verifier");
    try {
      await smartWalletRelayVerifier.methods.acceptToken(tokenAddress).send({from: accounts[0]});
    } catch (error) {
      console.error(error);
    }
    console.log("Adding token with address " + tokenAddress + " to allowed tokens on custom smart deploy verifier");
    try {
      await customSmartWalletDeployVerifier.methods.acceptToken(tokenAddress).send({from: accounts[0]});
    } catch (error) {
      console.error(error);
    }
    console.log("Adding token with address " + tokenAddress + " to allowed tokens on custom smart wallet relay verifier");
    try {
      await customSmartWalletRelayVerifier.methods.acceptToken(tokenAddress).send({from: accounts[0]});
    } catch (error) {
      console.error(error);
    }
  }
  console.log("Done!");
}
EOF

truffle exec allowTokens.js

rm allowTokens.js
rm truffle-config.js
