#!/bin/bash -e

rm -rf ./dist/
yarn truffle-compile
yarn extract_abi
yarn generate

mkdir -p src/cli/compiled/

CONTRACTS="RelayHub Penalizer SmartWallet SmartWalletFactory CustomSmartWallet CustomSmartWalletFactory VersionRegistry RelayVerifier DeployVerifier RelayVerifierCustomWallet DeployVerifierCustomWallet TestVerifierEverythingAccepted TestDeployVerifierEverythingAccepted"
BUILDFOLDER=./build/contracts
OUTFOLDER=./src/cli/compiled
for c in $CONTRACTS; do
  echo copy $OUTFOLDER/$c.json
  cp $BUILDFOLDER/$c.json $OUTFOLDER
done


#these files are created for packing only (removed by "postpack")
for c in RelayProvider RelayClient RelayEvents Configurator TestEnvironment; do
  echo gen ./$c.ts:
  (echo "// generated during pack";echo "export * from './src/relayclient/$c'") > $c.ts
done
echo gen ./Utils.ts:
(echo "// generated during pack";echo "export * from './src/common/Utils'") > Utils.ts

tsc

cp -r types dist/
