#!/bin/bash -e

rm -rf ./dist/

#these files are created for packing only (removed by "postpack")
for c in RelayProvider RelayClient RelayEvents Configurator TestEnvironment; do
  echo gen ./$c.ts:
  (echo "// generated during pack";echo "export * from './src/relayclient/$c'") > $c.ts
done
echo gen ./Utils.ts:
(echo "// generated during pack";echo "export * from './src/common/Utils'") > Utils.ts

tsc

cp -r types dist/
