#!/bin/bash

echo "Building jsrelay server"

cd jsrelay && npx webpack && cd ../

echo "Starting jsrelay server"

node dist/src/cli/commands/enveloping.js relayer-run --config jsrelay/config/relay-config.json
